sudo: false
language: rust
cache: cargo

# necessary for kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # required for the --verify flag of kcov
      - libiberty-dev

rust:
  - nightly
  - beta
  - stable
  - 1.12.0

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$PATH:$HOME/.local/bin
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
after_success:
  # NB: only upload linux master docs to avoid conflicting with the osx build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo --only stable doc-upload; fi
  # NB: kcov only works on linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./ci/install-kcov.sh && ./ci/coverage.sh; fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - RUSTFLAGS="-C link-dead-code" # Enable better code coverage at the cost of binary size

notifications:
  email:
    on_success: never

os:
  - linux
  - osx
